## **Let's dive deep into Feed-Forward Networks!**
🦫KURW.AI💗

---

Venchislaw 2024.

### 1) Intro for Nerds
---

Human brain is incredible.<br>
It can learn complex patterns by building complex neuron connections.<br>
Yet we don't 100% now how brain works, we can build digital model of neuron and __network of neurons__<br>
To build digital model of Neuron we should understand how biological one works.<br>
I'm not a neuro-scientist, but I remember biology lesson at school about neurons<br>
<img src="https://miro.medium.com/v2/resize:fit:1400/1*K1ee1SzB0lxjIIo7CGI7LQ.png" width=30%><br>
Ommiting biological details we can describe neuron in few words as a cell recieving information with dendrites from past neurons and either "firing" electrical signal or not. Neuron then passes its processed information with synapses to the following neurons.<br>
Once again, model requires simplification, so we can look at a neuron as at a "tiny unit that intakes some information and returns processed inputs.<br>
The only question is "processing".<br>
What should we do?<br>
Neural Network consists of neurons, so it's better to think about one single unit.<br>

### 2) Neuron Model

---

To the moment of building neuran model humanity was already aware of "linear models".<br>
That's exactly what scientists decided to use.<br>
For the model of neuron they picked linear model with "activation function" applied to it.<br>
If you don't remember how linear model looks I can remind you quickly:<br>
$$a = \sum^n_{i=0} \theta _ix_i$$
where $x_0 = 1$ (to learn bias)<br>
What is this "activation function"?<br>
Biological Neuron is binary, it's either on or off.<br>
Activation Function in this case is a __step function__.<br>
It's 1 for input > threshold and 0 for input < threshold.<br>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/HardLimitFunction.png/400px-HardLimitFunction.png" width=30%><br>
As you can see from this picture we have a 0 threshold.<br>
However, custom threshold is not a problem for us.<br>
**Threshold = - bias**
This is to say, our linear computation already includes threshold.<br>

### 3) Perceptron

Perceptron is the first model of biological neuron.<br>
Invented in 1958 it applied all practices described above with a pretty interesting learning rule.<br>
Perceptron model is used for supervised binary classification task.<br>
__How it works:__<br>
It does absolutely the same thing, but to tune hyperparameters it follows the following rule:<br>
- If prediction is correct (1-1 or 0-0) we do not change weights
- If prediction is wrong:
- - False Positive:<br>
        This means our linear output is over the threshold<br>
        We subtract scaled input feature vector from parameters<br>
- - False Negative:<br>
        This means our linear output is under the threshold<br>
        We add up scaled input feature vector to parameters<br>

**NOTE: Perceptron process each sample individually.**<br>
This method tunes parameters close enough to the desired values.<br>
### Let's build one!

In [18]:
import numpy as np

In [21]:
"""
Here I generate simple dummy dataset.<br>
"""
np.random.seed(23)

num_samples = 1000
num_features = 10

X = np.random.randn(num_samples, num_features)
weights = np.random.randn(num_features)
bias = 0.5
y = (np.dot(X, weights) + bias > 0).astype(int)

print("Shapes:")
print(X.shape, y.shape)
print("="*50)
print(X[:5], y[:5])
print("="*50)
unique, counts = np.unique(y, return_counts=True)
print(np.asarray((unique, counts)).T)

Shapes:
(1000, 10) (1000,)
[[ 0.66698806  0.02581308 -0.77761941  0.94863382  0.70167179 -1.05108156
  -0.36754812 -1.13745969 -1.32214752  1.77225828]
 [-0.34745899  0.67014016  0.32227152  0.06034293 -1.04345    -1.00994188
   0.44173637  1.12887685 -1.83806777 -0.93876863]
 [-0.20184052  1.04537128  0.53816197  0.81211867  0.2411063  -0.95250953
  -0.13626676  1.26724821  0.17363364 -1.22325477]
 [ 1.41531998  0.45771098  0.72887584  1.96843473 -0.54778801 -0.67941827
  -2.50623032  0.14696049  0.60619549 -0.02253889]
 [ 0.01342226  0.93594489  0.42062266  0.41161964 -0.07132392 -0.04543758
   1.04088597 -0.09403473 -0.42084395 -0.55198856]] [0 0 1 0 1]
[[  0 478]
 [  1 522]]


In [23]:
"""
And Here I build Perceptron Neuron!
"""

class Perceptron:
    def __init__(self):
        self.bias = 0

    def fit(self, X, y):
        self.weights = np.zeros((1, X.shape[1]))

        for sample in zip(X, y):
            prediction = np.dot(self.weights, sample[0]) + self.bias
            activated = prediction > 0

            self.weights += (sample[1] - activated) * sample[0]
            self.bias += (sample[1] - activated) * 1
        
        return self.weights, self.bias
    
    def predict(self, X):
        prediction = np.dot(self.weights, X.T) + self.bias
        return np.array(prediction > 0).astype(int)

In [24]:
perceptron = Perceptron()
perceptron.fit(X, y)

(array([[-13.58053614,  -0.07006142,  -0.82743697,  10.69942632,
           1.26320988,  -8.41174634,   2.87887913,  -6.40411674,
           6.93203191,  -4.31050118]]),
 array([2]))

In [31]:
y_pred = perceptron.predict(X).flatten()

In [33]:
wrong = 0
for pair in zip(y, y_pred):
    if pair[0] != pair[1]:
        wrong += 1
    
print(wrong)

73


73 Misclassifications are not bad, but...<br>
This is the training set it's seen.

### 4) Weakness of Perceptrons.

Perceptrons are not suitable for neural networks.<br>
1) Good Weights do not guarantee good outputs.
2) Sample-by-sample processing is inefficient for larger scale
3) Learning Rule of perceptron can not be scaled for multi-layer architecture (of a neural net)

You can hear people calling Feed-Forward Neural Network an **MLP (Multi-Layer Perceptron)**, but it's wrong<br>
They have nothing to do with Perceptron unit.<br>
This is one of those historical-convention naming issues (like one with Logistic Regression).<br>
They use gradient-descent for updates and the chain rule...<br>
Oops, spoiler here!

### 5) Linear Model with fancy activators.

**This is a paid content. Subscribe to KurwAI Plus to read premium guides.**<br>
F.cking with Ya, Work in progress!

<p align="center">
<img src="https://static-00.iconduck.com/assets.00/beaver-emoji-2048x2019-61w8w8mn.png" width=10%><br>
KurwAI Guides.<br>
MIT License.
</p>